name:                oas
version:             0.1.0.0
github:              "herulume/oas"
license:             MIT
author:              "Eduardo Jorge"
maintainer:          "herulume@protonmail.com"
copyright:           "2019 Eduardo Jorge"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Implementing open api schema 3.0 in Haskell
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/herulume/oas#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2.2 && < 2.3
- microlens >= 0.4.11 && < 0.5
- microlens-th >= 0.4.3 && < 0.5
- aeson >= 1.4.4 && < 1.5
- text >= 1.2.3 && < 1.3
- unordered-containers >= 0.2.10 && < 0.3
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror

tests:
  oas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Werror
    dependencies:
    - oas
    - hspec                >= 2.7.1 && < 2.8
