name:                oas
version:             0.1.0.0
github:              "herulume/oas"
license:             BSD3
author:              "Eduardo Jorge"
maintainer:          "herulume@gmail.com"
copyright:           "2019 Eduardo Jorge"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/herulume/oas#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- microlens
- microlens-th
- aeson
- text
- unordered-containers
library:
  source-dirs: src

tests:
  oas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oas
    - hspec
