version: 2.1
orbs:
  github: haskell-works/github-release@1.0.0

jobs:
  get-version:
    working_directory: /tmp/cci-test
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: pwd
      - run: mkdir -p workspace
      - run:
          name: set vars
          command: >
            echo "export OAS_VERSION=$(grep '^version: *[0-9]' package.yaml | cut -d':' -f2 | tr -d ' ')" >> workspace/env-vars
      - run: cat workspace/env-vars >> $BASH_ENV
      - run: echo "$OAS_VERSION"
      - persist_to_workspace:
          root: workspace
          paths:
            - env-vars

  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          # We run tests on the build step because CircleCI workflows actually suck (:
          # By sucking I mean, they suck the fpco/stack-build image in every single job.
          # According to some forum it won't if that machine doing the build already contains the docker image.
          # Obviously all of them are filled with NodeJS containers.
          name: Run tests
          command: stack --no-terminal test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - save_cache:
          name: Cache Dependencies
          key: cci-oas-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

  coverage:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Stack build with coverage
          command: stack build --coverage --no-terminal
      - run:
          name: Run tests to gather coverage data
          command: stack test --coverage --no-terminal
      - run:
          name: Move HPC files to a temporary directory
          command: |
            mkdir -p /tmp/hpc
            mv "$(stack path --no-terminal --local-hpc-root)" /tmp/hpc
      - store_artifacts:
          path: /tmp/hpc

  mkdocs:
    working_directory: /tmp/cci-test
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/cci-test/workspace
      - run: cat workspace/env-vars >> $BASH_ENV
      - run: echo "$OAS_VERSION"
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Run haddock and move haddock files to a temporary directory
          command: |
            stack --no-terminal haddock
            mkdir -p /tmp/haddock
            mv "$(stack --no-terminal path --local-doc-root)/oas-$OAS_VERSION" /tmp/haddock
      - store_artifacts:
          path: /tmp/haddock

workflows:
  version: 2
  all:
    jobs:
      - build
      - get-version
      - coverage
      - mkdocs:
          requires:
            - build
            - get-version
      - github/release:
          requires:
            - mkdocs
            - get-version
          workspace-root: /tmp/cci-test/workspace
          attach-workspace: true
          before-release:
            - run: cat /tmp/cci-test/workspace/env-vars >> $BASH_ENV
            - run: echo "$OAS_VERSION"
          tag: v$OAS_VERSION
          title: Release v$OAS_VERSION
          filters:
            branches:
              only: release
