version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          # We run tests on the build step because CircleCI workflows actually suck (:
          # By sucking I mean, they suck the fpco/stack-build image in every single job.
          # According to some forum it won't if that machine doing the build already contains the docker image.
          # Obviously all of them are filled with NodeJS containers.
          name: Run tests 
          command: stack --no-terminal test
      - run:
          name: Install executable
          command: stack --no-terminal install
      - save_cache:
          name: Cache Dependencies
          key: cci-oas-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

  coverage:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Stack build with coverage
          command: stack build --coverage --no-terminal
      - run:
          name: Run tests to gather coverage data
          command: stack test --coverage --no-terminal
      - run:
          name: Move HPC files to a temporary directory
          command: |
            mkdir -p /tmp/hpc
            mv "$(stack path --no-terminal --local-hpc-root)" /tmp/hpc
      - store_artifacts:
          path: /tmp/hpc

  mkdocs:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - cci-oas-haskell-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Run haddock and move haddock files to a temporary directory
          command: |
            stack --no-terminal haddock
            mkdir -p /tmp/haddock
            mv "$(stack --no-terminal path --local-doc-root)/oas-0.1.0.0" /tmp/haddock
      - store_artifacts:
          path: /tmp/haddock

workflows:
  version: 2
  all:
    jobs:
      - build
      - coverage
      - mkdocs:
          requires:
            - build
